// eslint-disable-next-line
export default {
  // courses
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",
  DELETE_COURSE: "DELETE_COURSE",
  LOAD_COURSES: "LOAD_COURSES",
  //authors
  CREATE_AUTHOR: "CREATE_AUTHOR",
  DELETE_AUTHOR: "DELETE_AUTHOR",
  LOAD_AUTHORS: "LOAD_AUTHORS",
};
